### ISSUE TITLE
Request for Codec.Create with Format of byte []

### ISSUE THREAD

**Issue by fluxlife** [jet/FsCodec#53]
I may be misunderstanding this but if you wanted to supply your own custom FsCodec to Equinox you can `FsCodec.Codec.Create(encoder, decoder)`. However, Equinox expects a a `'Format` of `byte[]` ... i.e. `IEventCodec<'Event,byte [], 'Context>` but it seems that `FsCodec.Codec.Create` will only allow you to construct a `IEventCodec<'Event, string, 'Context>`. Notice `string` vs `byte []`.

I am sure the work around is to fully implement `IEventCodec`, but would be nice to have a equinox  compatible short hand constructor.

**Comment by bartelink** [comment]
https://github.com/jet/FsCodec/blob/master/src/FsCodec.SystemTextJson/Interop.fs#L51 does the requisite mapping

Lets leave this ticket open until someone gets around to planting a mention of it in the README.md (arguably it should go in Equinox's DOCUMENTATION.md) ;)
