### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by vchekan** [jet/FsCodec#9]
Would be nice to have some examples as section in readme.md or a folder. It is hard to make first impression of what this library is from description as it stands now.

Also:

What is " versionable serialization strategies"?

"The converters are employed in diverse systems across Jet, both for [de]coding Events within Event-sourced streams, and for HTTP requests/responses. As such, format changes need to be interoperable"
It does not matter, is it events or configuration or reports. I'd reduce it to "converters are used in production code in Jet, so any changes must produce backward compatible json". That explains it all without artificial limits is scope to events processing.

"Less [converters] is more - has a converter really proved itself broadly applicable ?"
I do not understand referred link. What refactoring rule of thumb is doing here?

"this is not the final complete set of converters; Json.net is purposefully extensible and limited only by your imagination, for better or worse"
Without example, it is hard to understand what it is all about.

"Concrete Converter implementations"
Would be nice to provide direct link.

"Naturally, the library naturally"
:)

"going that extra mile here is unwarranted for now given the implementation is in F#"
Do not understand

**Comment by bartelink** [comment]
Thanks for the feedback - all good points that would definitely help this readme. Will get around to this in due course. Some quick responses before I do and/or someone contributes them ;) :-

- The point re versionable is that the OOTB json.net impl mapping unions to arrays of fields, and if you reorder them or add one in the middle, it all goes horribly wrong. I've seen quite a few other converters have the same weakness. Similar points re tuple to array converters.

- I see your point about the divers systems verbiage; I was attempting to convey that the converter works (and needs to work) not just for round-tripping for event sourcing, but also support validation in webapi etc.

**Comment by bartelink** [comment]
Hey - if you have the time, I would appreciate a re-review - I've removed most of the nonsense phrases, but new ones keep sprouting from my fingers anew! (still need to add a section on `JsonIsomorphism`)

**Comment by bartelink** [comment]
Assuming no time - please feel free to re-open ;)
